import React from "react";
import AddItem from '../Components/AddItem'
import {db} from '../Services/Config'
import {addDoc,collection, doc} from 'firebase/firestore'

function Crud(){

const addOrEdit = async (data) =>{    
    // V8: await db.collection('velas').doc().set(object);
    //V9 - with autogenerated Id
    await addDoc(collection(db, "velas"), data);
    console.log('nueva vela agregada', data)
}


    return(
        <>        
        <AddItem addOrEdit={addOrEdit}/>        
        </>
    )
}

export default Crud